# Generated by Django 4.2 on 2025-01-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("birds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now=True, verbose_name="观察时间")),
                ("location", models.CharField(max_length=255, verbose_name="观察地点")),
                ("description", models.TextField(verbose_name="观察现象")),
                (
                    "additional_notes",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                (
                    "observation_data",
                    models.CharField(max_length=255, verbose_name="观察数据"),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=255, verbose_name="预测结果"),
                ),
                (
                    "bird",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="birds.bird",
                    ),
                ),
            ],
            options={
                "verbose_name": "观察数据",
                "verbose_name_plural": "观察数据",
            },
        ),
    ]
