# Generated by Django 4.2 on 2025-01-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bird",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("images", models.CharField(max_length=255, verbose_name="鸟类图片")),
                ("name", models.CharField(max_length=50, verbose_name="鸟类名称")),
                ("order", models.CharField(max_length=50, verbose_name="目")),
                ("family", models.CharField(max_length=50, verbose_name="科")),
                ("genus", models.CharField(max_length=50, verbose_name="科")),
                ("size", models.CharField(max_length=100, verbose_name="体型描述")),
                ("plumage", models.CharField(max_length=255, verbose_name="羽毛描述")),
                ("habitat", models.CharField(max_length=100, verbose_name="栖息地分布")),
                ("distribution", models.CharField(max_length=255, verbose_name="地理分布")),
                ("iucn_status", models.CharField(max_length=50, verbose_name="保护等级")),
                ("love_number", models.IntegerField()),
                ("observations_number", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True, verbose_name="添加时间")),
            ],
            options={
                "verbose_name": "鸟类数据",
                "verbose_name_plural": "鸟类数据",
            },
        ),
    ]
