# Generated by Django 4.2 on 2025-01-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("observations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("pwd", models.CharField(max_length=32, verbose_name="密码")),
                (
                    "sex",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女")],
                        max_length=10,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="年龄")),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="电话号码"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=32, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "resume",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="简介"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="img/avatar/default.png",
                        max_length=255,
                        upload_to="img/avatar/%Y/%m/%d/",
                        verbose_name="用户头像",
                    ),
                ),
                ("pub_date", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                (
                    "love",
                    models.ManyToManyField(
                        related_name="love", to="observations.observation"
                    ),
                ),
                (
                    "observation",
                    models.ManyToManyField(
                        related_name="observation", to="observations.observation"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户数据",
                "verbose_name_plural": "用户数据",
            },
        ),
    ]
