# Generated by Django 3.2.9 on 2024-05-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_mediasocial_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='media',
            field=models.ManyToManyField(related_name='media', to='media.MediaSocial'),
        ),
    ]
