# Generated by Django 3.2.9 on 2024-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='media',
        ),
    ]
