# Generated by Django 3.2.9 on 2024-05-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userinfo_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='img/avatar/default.png', max_length=255, upload_to='img/avatar/%Y/%m/%d/', verbose_name='用户头像'),
        ),
    ]
