# Generated by Django 3.2.9 on 2024-05-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, null=True, verbose_name='性别'),
        ),
    ]
