# Generated by Django 3.2.9 on 2024-05-15 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_text', models.TextField(blank=True, null=True, verbose_name='帖子内容')),
                ('release_time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('media_support', models.IntegerField(default=0, verbose_name='点赞数')),
                ('media_dislike', models.IntegerField(default=0, verbose_name='不喜欢数')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_image', to='user.userinfo')),
            ],
            options={
                'verbose_name': '媒体数据',
                'verbose_name_plural': '媒体数据',
            },
        ),
    ]
