# Generated by Django 3.2.9 on 2024-05-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediasocial',
            name='user',
        ),
        migrations.AddField(
            model_name='mediasocial',
            name='user',
            field=models.ManyToManyField(to='user.UserInfo'),
        ),
    ]
