# Generated by Django 3.2.9 on 2024-05-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userinfo_media'),
        ('media', '0003_remove_mediasocial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediasocial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user.userinfo', verbose_name='用户'),
        ),
    ]
